### PR TITLE
Issue #3 always passing test type

### LINKED ISSUE #3: Support an always-passing exercise type
We need it to implement hidden exercises. It should look like this: 

```yaml
type: display
query: select * from peliculas
```

@NadiaFinzi

### PR DESCRIPTION
**Pull request by flbulgarelli**
Fixes #3 
Related to #8

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Looks good!

**Comment by flbulgarelli** [comment]
Just a question: are given query results being rendered? 

For example, when send this test: 

```
"type: display\nseed: create table foo (id integer); insert into foo values (1);insert into foo values (100);\nquery: select * from foo;"
```

I am not being able to see expected results on a local test: 

```
HTTP/1.1 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
Content-Length: 668

{"testResults":[{"title":"Dataset 1","status":"passed","result":"<style>\n  table.sqlite_success {\n    width: auto;\n    border: none;\n  }\n  table.sqlite_success tr:nth-child(even) {\n    background-color: #DDDDDD;\n  }\n  table.sqlite_success tr:nth-child(odd) {\n    background-color: #FFFFFF;\n  }\n  table.sqlite_success th {\n    color: white;\n    font-weight: bold;\n    background-color: #BBBBBB;\n  }\n  table.sqlite_success td {\n    width: auto;\n    text-align: left;\n  }\n</style>\n\n<h5>Correct Query!</h5>\n<table class=\"table table-bordered sqlite_success\">\n  <thead>\n  <tr>\n  \n  </tr>\n  </thead>\n\n  <tbody>\n  \n  </tbody>\n</table>\n"}]}
```

It says that query is right, but no results are displayed - the table is empty.

**Comment by laendoor** [comment]
Hummm... Probably when student's solution match with expected, datasets are not showing. I don't remember if it is a feature or a bug :P

We can do that always show results or just when `type: display`. As you prefer. Make me an issue with you preference and I'll do it.

**Comment by flbulgarelli** [comment]
Haha, got it!

**Pull request merged**
